name: build_1.21.1

jobs:
  build_1.21.1:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "microsoft"

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: delete old nightly release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: build_1.21.1
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true
        continue-on-error: true

      - name: create nightly release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build_1.21.1
          name: Nightly Build
          body: |
            Automatic nightly build.

            Commit: ${{ github.sha }}
          prerelease: true
          files: build/libs/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}