name: build_1.21.1

on:
  push:
    branches:
      - "1.21.1"
  pull_request:
    branches:
      - "1.21.1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_1_21_1:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "microsoft"

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-the-models-1.21.1
          path: build/libs/
